### ISSUE TITLE
dockerize lorax

### ISSUE THREAD

**Issue by joelb123** [LegumeFederation/lorax#142]
Lorax would be far cleaner to install with docker.  Several dependency issues would also be easily solved by dockerizing.

**Comment by svengato** [comment]
Done, in commit fbc2cbf1e39aa959c72b9e1015a767c34bc58c15.
Then merged the `funnotate` branch into `master`.

The last Dockerized version (`containerize` branch) before Funnotate adaptations was 5bafc556fb9e92cf93dc513bd220663272911fd7.
The last non-containerized version was 1e595c298ee02c7039268281e94568fece01de10.
See the history for details.
