### ISSUE TITLE
some polypeptide name changes in chado have lorax a bit out of sync

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/lorax#25]
the effects are subtle, but basically a few species are not identified correctly when the trees are returned. This is just an effect I didn't anticipate when making the changes in the db, so my bad.
not the end of the world but would be nice to get fixed when we can. The two species impacted are "cajca" and "cicar". For "cajca" all that needs to be done is to have a ".1" appended to the existing ids in the fastas for the gene families (I think that's the only place they exist in lorax, though not %100 sure). For "cicar" not only does ".1" need to be appended, but also the existing "cicar" prefix should become "cicar.CDCFrontier." as in "cicar.CDCFrontier.Ca_19912.1"

**Comment by joelb123** [comment]
This isn't a lorax issue, but rather an issue with the input datasets. Input datasets will be updated on the download site as appropriate for LIS.
