### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/lorax#79]
Hi @adf-ncgr and @joelb123 
I am trying to use the lorax build a gene tree and got an gateway timeout error.

Here is the annotation job link: https://legumeinfo.org/annot/job/H9M8L

**Comment by adf-ncgr** [comment]
@jd-campbell thanks for reporting this. It just occurred to me that the most likely reason for this behavior is that lorax services were running on legumefederation.org and may well have been compromised by the shenanigans we pulled to establish the new legumefederation.org ;
lorax services are certainly not running on the new legumefederation.org but in theory they may still be running on v1.legumefederation.org so I will try switching the config and see if that solves it for now. longer term, we'll probably want to find a new home.

**Comment by adf-ncgr** [comment]
@jd-campbell this took a bit longer to bounce between myself and @joelb123 to handle the things needed to cope with the changes made to the older legumefederation.org site (now known as v1.legumefederation.org to the world but as legfed-stage among the inner circle). But, it should be working now (and to prove it I made your tree) : 
![image](https://user-images.githubusercontent.com/2009605/48876546-d996b500-edbb-11e8-9e0d-fb8c967eb787.png)
thanks again for alerting us to the situation!
